AWSTemplateFormatVersion: "2010-09-09"
Description: "This template is to create EC2 instance in AWS"
Parameters:
  InstanceType:
    Type: String
    Description: "Size of the EC2 machine"
    Default: t2.micro
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "SSH into EC2 instance"
  ImageId:
    Type: AWS::EC2::Image::Id
    Description: "Image ID for EC2 machine"
    Default: ami-0ed9277fb7eb570c9
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC ID"
Resources:
  DummyServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref SSHKey
      SecurityGroupIds:
        - !GetAtt
          - SSHSecurityGroup
          - GroupId
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22