- name: Deploying servers on AWS with CloudFormation
  hosts: servers
  connection: local
  gather_facts: False
  become: no
  vars_files:
    - "../inventory/group_vars/env.yml"
  tasks:
    #This task is neccessary to work with dynamic inventory and
    #provide group_vars before actually provisioning
    - name: Add localhost to the group
      add_host:
        name: localhost
        groups: servers
      tags:
        - always

    - name: Provisioning in AWS using cloudformation template
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: "present"
        region: "{{ aws_region }}"
        disable_rollback: true
        template: "../files/server.yml"
        template_parameters:
          ImageId: "{{ aws_image }}"
          SSHKey: "{{ aws_key_name }}"
          InstanceType: "{{ aws_instancetype }}"
          VpcId: "{{vpc_id}}"
      when: hosting == "Create"

    - name: Delete existing AWS cloudformation stack
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: "absent"
        region: "{{ aws_region }}"
        disable_rollback: true
      when: hosting == "Delete"